events {}

http {
    upstream backend_app {
        server backend:5000;
    }

    upstream voice_gateway {
        server voice-gateway:8001;
    }

    server {
        listen 8080;

        location /incoming-call {
            proxy_pass http://voice_gateway;
            proxy_set_header Host $host;
        }

        location /media-stream {
            proxy_pass http://voice_gateway;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        location /metrics {
            proxy_pass http://voice_gateway;
        }

        location /active-calls {
            proxy_pass http://voice_gateway;
        }

        location /session/ {
            proxy_pass http://voice_gateway;
        }

        location / {
            proxy_pass http://backend_app;
        }
    }
}
